#pragma once

#define SUCCESS (0)
#define FAILURE_BADPARAM (-1)
#define FAILURE_BADALLOC (-2)

#define AVX1_ALIGNMENT (16)
#define AVX2_ALIGNMENT (32)

#define AVX2_FLOAT_STRIDE (8)
#define AVX2_FLOAT_BATCH_MASK (~7u)
#define AVX2_FLOAT_REMAIN_MASK (7u)

#define AVX2_DOUBLE_STRIDE (4)
#define AVX2_DOUBLE_BATCH_MASK (~3u)
#define AVX2_DOUBLE_REMAIN_MASK (3u)

#define MAX_VECTORWISE_ALIGNMNET_INCX (4096)
#define MAX_AGGREGATE_BATCHING (64)

#define MAX_KERNEL_SIZE (65537)
#define MAX_DATA_SIZE (16777216)